#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "revealjs"
name = "Reveal.js"
description.en = "HTML Presentation Framework"
description.fr = "HTML Presentation Framework"

version = "5.1.0~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://revealjs.com/"
demo = "https://revealjs.com/"
admindoc = "https://revealjs.com/installation/"
code = "https://github.com/hakimel/reveal.js"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/reveal"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/hakimel/reveal.js/archive/36daed927e44df5eb7841f46f13e2589e69d57b7.zip"
    sha256 = "c084ade0b2fc4253596738f59da8084744c44ece23dc7f8815c775221683ceb5"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
